### ISSUE TITLE
Convert changes with no classes/teachers to messages

### ISSUE THREAD

**Issue by AltNico** [vertretungsplanme/substitution-schedule-parser#18]
Currently, changes with no course/teacher are hidden in the Android client.
## Experienced behaviour

Changes from LegionBoard that are not assigned to any course or teacher are used as such.
## Wanted behaviour

If a change has no course or teacher assigned, it is converted to a message.

Related to #16.

**Comment by johan12345** [comment]
Thanks for opening the issue! As I said, it is probably best to implement this inside the `LegionBoardParser` instead of in the Android client, because
- as far as I know, this situation does not occur in the other supported systems (-> they don't have any changes without class _and_ teacher)
- it will then also work without additional modifications in other (future) clients

**Comment by johan12345** [comment]
Changes with no classes assigned should now be shown in version 3.1.0 of the Android client.
